### ISSUE TITLE
ParseInt error when scanning table

### ISSUE THREAD

**Issue by honza** [rach/pome#22]
```
2016/01/05 11:42:24 Starting Pome 0.1.0
2016/01/05 11:42:24 Application will be available at http://127.0.0.1:2345
2016/01/05 11:42:24 sql: Scan error on column index 3: converting string "1.1198464e+07" to a int: strconv.ParseInt: parsing "1.1198464e+07": invalid syntax
```

Using version 804786ebf1ed5665049178b657f425b612b8c66d

**Comment by ober** [comment]
Hit by it too.

**Comment by rach** [comment]
I will try to get that fixed asap. I suspect that some of the sql query needs some adjustment as the Go Sql lib cannot handle the conversion.

**Comment by rach** [comment]
It seems like the problem come from SUM used for the database size. SUM of bigint return a numeric type. I don't think that we will support db above int64 size 

```
 select pg_size_pretty(9223372036854775807);
 pg_size_pretty
----------------
 8388608 TB
(1 row)
```

I now cat the result to bigint so it should solve the problem. 
I wasn't not able to reproduce the bug even when replacing query with `SELECT 1.1198464e+07 , 1.1198464e+07::numeric` so it will be amazing if you could test https://github.com/rach/pome/commit/b051abf4f978ed48baa94ca3e5aeca9fd4388dcb

thanks

**Comment by honza** [comment]
Unfortunately, the problem persists:

```
2016/01/06 10:13:54 Starting Pome 0.1.1
2016/01/06 10:13:54 Application will be available at http://127.0.0.1:2345
2016/01/06 10:13:54 sql: Scan error on column index 3: converting string "1.1198464e+07" to a int: strconv.ParseInt: parsing "1.1198464e+07": invalid syntax
```

The database is pretty small, like 300MB. 

I'm using Postgresql 9.4.5 on OSX.

**Comment by rach** [comment]
I will publish a verbose mode later tonight, I realize that I added the cast on the wrong db query.
Base on the `index 3` then it means that the problem appear on TableBloat.
Thanks for trying and your patience, I'll try get that fixed asap.

**Comment by internetuser2008** [comment]
Getting same error on Mac OSX Postgres 9.4.4

2016/01/06 13:52:21 Starting Pome 0.1.1
2016/01/06 13:52:21 Application will be available at http://127.0.0.1:2345
2016/01/06 13:52:21 sql: Scan error on column index 3: converting string "2.031616e+06" to a int: strconv.ParseInt: parsing "2.031616e+06": invalid syntax

**Comment by jmealo** [comment]
Same issue using the latest Go and Pome on Ubuntu 14.04 (64-bit).

**Comment by ThisIsMissEm** [comment]
I'm getting similar, with `2016/01/07 03:19:55 sql: Scan error on column index 3: converting string "4.145152e+06" to a int: strconv.ParseInt: parsing "4.145152e+06": invalid syntax`

**Comment by honza** [comment]
The fix works for me, thanks. :sparkles:

**Comment by rach** [comment]
Great. Thanks for testing it. I should have been more careful about the types of some of the SQL query.
